# Generated by Django 5.2.7 on 2025-10-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_meetingpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingpoint',
            name='user',
        ),
    ]
