# Generated by Django 5.2.7 on 2025-10-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_meetingpoint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpoint',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
