# Generated by Django 5.2.7 on 2025-10-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_meetingpoint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoint',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
