# Generated by Django 5.2.7 on 2025-10-31 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_meetingpoint_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpoint',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
