# Generated by Django 5.2.7 on 2025-11-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_meetingpoint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoint',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='اسم الشخص المسؤول عن تنفيذ النقطة', max_length=100, null=True),
        ),
    ]
