# Generated by Django 5.2.7 on 2025-11-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_meetingpoint_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpoint',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
