# Generated by Django 5.2.7 on 2026-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_meetingpoint_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundShipmentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_nbr', models.CharField(db_index=True, max_length=255)),
                ('facility', models.CharField(db_index=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inbound Shipment Remark',
                'verbose_name_plural': 'Inbound Shipment Remarks',
                'unique_together': {('shipment_nbr', 'facility')},
            },
        ),
    ]
