# Generated by Django 5.2.7 on 2026-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_inbound_shipment_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSheetCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('data', models.JSONField(default=list)),
                ('source_file_path', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel Sheet Cache',
                'verbose_name_plural': 'Excel Sheet Caches',
            },
        ),
    ]
