# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_excel_sheet_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_path', models.CharField(db_index=True, max_length=512, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Data Cache',
                'verbose_name_plural': 'Dashboard Data Caches',
            },
        ),
    ]
