# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_dashboard_data_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseAccountOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(db_index=True, max_length=255)),
                ('account', models.CharField(db_index=True, max_length=255)),
                ('inbound', models.PositiveIntegerField(default=0)),
                ('outbound', models.PositiveIntegerField(default=0)),
                ('clearance', models.PositiveIntegerField(default=0)),
                ('occupied_location', models.PositiveIntegerField(default=0)),
                ('transportation', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse & Account Row',
                'verbose_name_plural': 'Warehouse and Account Overview',
                'ordering': ('warehouse', 'account'),
            },
        ),
    ]
