# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_warehouse_account_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(db_index=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacity Volume (Warehouse)',
                'verbose_name_plural': 'Capacity Volume (Warehouses)',
                'ordering': ('warehouse',),
            },
        ),
    ]
