# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_capacity_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaccountoverview',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
