# Generated by Django 5.2.7 on 2026-03-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_warehouseaccountoverview_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseaccountoverview',
            options={'ordering': ('id',), 'verbose_name': 'Warehouse & Account Row', 'verbose_name_plural': 'Warehouse and Account Overview'},
        ),
    ]
