# Generated by Django 5.2.7 on 2026-03-16 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_warehouseimportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='clearance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='inbound',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='occupied_location',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='outbound',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='transportation',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseaccountoverview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
